http://www.elasticsearch.org/[Elasticsearch] is a highly scalable open-source full-text search and analytics engine. It allows you to store, search, and analyze big volumes of data quickly and in near real time. It is generally used as the underlying engine/technology that powers applications that have complex search features and requirements.

The Grails ElasticSearch plugin intends to implement a simple integration with Grails of the Open Source Search Engine ElasticSearch, which is based on Lucene and provide distributed capabilities.

=== Features

* Maps domain classes to their corresponding index in Elasticsearch
* Provides an ElasticSearch service for cross-domain searching
* Injects domain class methods for specific domain searching, indexing and unindexing
* Automatically mirrors any changes made through GORM to the index
* Allow to use the Groovy Content Builder DSL for search queries
* Support for term highlighting


In this guide, you will learn how to use Grails Elasticserach plugin to create index in Elasticsearch for faster search.