* To install the plugin add following properties to `build.gradle`:

[source, groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[lines=26..27]
----
<1> Define Elasticsearch version.

* Also, add the following to `dependencies` block:

[source, groovy, indent=0]
----
include::{sourceDir}/build.gradle[lines=54..54]
----

* In order to connect Application to Elasticsearch, define Elasticsearch plugin configurations in `application.yml` as follows:

[source, groovy]
.grails-app/conf/application.yml
----
include::{sourceDir}/grails-app/conf/application.yml[lines=113..121]
----

<1> Hibernate datastore implementation should be watched for storage events.
<2> The plugin create a transport client that will connect to a remote ElasticSearch instance without joining the cluster.The `TransportClient` connects remotely to an Elasticsearch cluster using the transport module and communicates with them in round robin fashion on each action.
<3> Host address for `TransportClient` to connect to.
<4> Name of the Elasticsearch cluster.
<5> Determines if the plugin should reflect any database save/update/delete automatically on the ES instance. Default to false.
<6> Application should launch a bulk index operation upon startup.

